vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        poster_file:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /uploads/images/poster
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        video_file:
            uri_prefix: /uploads/videos
            upload_destination:  '%kernel.project_dir%/public/uploads/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
